name: GLuaFixer

on:
  pull_request:

jobs:
  Lint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
    with:
      config: "https://raw.githubusercontent.com/CFC-Servers/cfc_configs/master/gluafixer/glualint.json"
