name: GLuaFixer

on:
  pull_request:

jobs:
  Lint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml
    with:
      config: "CFC-Servers/github_action_workflows/.github/workflows/lint_glua.yml@feature/shareable"
